version: "3.7"

services:
    php:
        build: .docker/php-fpm
        volumes:
            - .:/app
            - ~/.composer:/.composer

    node:
        build: .docker/node
        volumes:
            - .:/app